
version: '2'

services:
  kepler0.example.com:
    container_name: kepler0.example.com
    image: kepler
    environment:
      - CONFIG_CONSORTIUM_MSPID=Org1MSP
    working_dir: /opt/gopath/src/github.com/vntchain/kepler
    command: kepler node start
    volumes:
        - ./data/org1/config/:/opt/gopath/src/github.com/vntchain/kepler/config

  kepler1.example.com:
    container_name: kepler1.example.com
    image: kepler
    environment:
      - CONFIG_CONSORTIUM_MSPID=Org2MSP
      - CONFIG_CONSORTIUM_PEERS={ "peer1" :{ "address":"192.168.9.33:8051","sn":"","eventAddress":"192.168.9.33:8053","tls":{"enabled":false,"clientAuthRequired":false,"clientKeyFile":"client.key","clientCertFile":"client.cer","rootcertFile":"root.cer"}} }
    working_dir: /opt/gopath/src/github.com/vntchain/kepler
    command: kepler node start
    volumes:
        - ./data/org2/config/:/opt/gopath/src/github.com/vntchain/kepler/config